"""add stats in user

Revision ID: 0f26df11f079
Revises: b457009740b6
Create Date: 2025-03-17 21:53:38.307201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f26df11f079'
down_revision: Union[str, None] = 'b457009740b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('solved_examples', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('correctly_solved_examples', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('completed_quests', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'completed_quests')
    op.drop_column('users', 'correctly_solved_examples')
    op.drop_column('users', 'solved_examples')
    # ### end Alembic commands ###
